### PR TITLE
Added headerFilter ColumnOption

### PR DESCRIPTION
**Pull request by DBremen**
Added a headerFilter option to the New-ColumnOption function. For the select headerFilter type the Out-TabulatorView function automatically populates the drop-down based on the unique values of the respective column.
Updated ShowChart.ps1 example to demo the headerFilter option.

### CODE REVIEW

**Comment by dfinke** [comment]
Nice. I just did a pass last night at filters, in a branch. Sounds like yours has more features, will compare. 

Thanks!

**Comment by dfinke** [comment]
Needs an extra . for the `ipmo` in ShowChart

Check out my branch for the filters, let's chat.

https://github.com/dfinke/OutTabulatorView/tree/dcfAddFiltering

**Comment by DBremen** [comment]
Hi Doug,
you are right. I changed it because I ran into an error when executing the ShowChart, but didn't fix it properly either. I have now added PSScriptRoot to make sure it works regardless of the current location.

**Comment by DBremen** [comment]
I will open a new pull request with some additional changes

**Pull request closed without merging**
